version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "workspace: "
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci: "
